### PR TITLE
Add @githubteacher vacation spot

### PR DESCRIPTION
**Pull request by githubteacher**
This adds a favorite vacation spot for @githubteacher.

@crichID, what do you think of this?

### CODE REVIEW

**Comment by crichID** [comment]
@githubteacher Portland, Maine? I hope you go in the summer!

**Comment by DanielSiefert** [comment]
Do you bring sweaters to the beach?

**Comment by githubteacher** [comment]
May is a fantastic time to go there!  It's a bit rainy but it's beautiful!

**Comment by githubteacher** [comment]
:+1:

**Pull request merged**
