### PR TITLE
Add @mierdin bio

### PR DESCRIPTION
**Pull request by Mierdin**
This adds a bio for @mierdin as requested in #12.

 Hey @crichID, what do you think of this bio? I would :heart: your thoughts on this.

### CODE REVIEW

**Comment by crichID** [comment]
@Mierdin this looks great to me! :rocket: :hammer:

**Comment by Mierdin** [comment]
@crichID Thank you! I worked on it tirelessly for weeks.

**Comment by Mierdin** [comment]
@brianatssat - Thanks! Fixed in https://github.com/githubteacher/foundations-05-19-2015/commit/2b2c41b1eaf07acc1d5e4c71eca936ed7e9531c8

**Comment by brianatssat** [comment]
Looks great :+1:

**Pull request merged**
